---
- name: "Install NGINX"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nginx
    - policycoreutils-python3

- name: "Configure NGINX"
  template:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf.j2
    owner: root
    group: root
    mode: 0644

- name: "Allow nginx reverse proxy communication on SELinux"
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: "Start and enable NGINX"
  systemd:
    name: nginx.service
    state: started
    enabled: true

- name: "Configuring firewall services step 1"
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - "http"

- name: "Configuring firewall services step 2"
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - 9090/tcp
    - 9093/tcp
    - 3000/tcp
  tags:
    - firew_config

- name: Set up forward packages across routers
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    sysctl_set: true
    state: present
    reload: true
...