---
- name: Setting node1_plug
  become: false
  shell: VBoxManage showvminfo "{{ node1 }}" | awk '($1=="UUID:"){print$2}'
  register: node1_plug_output
  delegate_to: hosted_machine
  run_once: yes

- name: Setting node2_plug
  become: false
  shell: VBoxManage showvminfo "{{ node2 }}" | awk '($1=="UUID:"){print$2}'
  register: node2_plug_output
  delegate_to: hosted_machine
  run_once: yes

- name: configure static route on hosted_machine
  command: "{{ item }}"
  with_items:
    - "ip route add {{ localnet }} via {{ frontend_dmz_ip }}"
  ignore_errors: true
  delegate_to: hosted_machine
  run_once: yes

- name: generating passwords for final-project
  ansible.builtin.set_fact:
    node1_plug: "{{ node1_plug_output.stdout }}"
    node2_plug: "{{ node2_plug_output.stdout }}"
    pcm_password: "{{ lookup('ansible.builtin.password', '/tmp/final-project/pcm_password', chars=['ascii_letters', 'digits', 'punctuation'], length=20) }}"
    mysql_root_password: "{{ lookup('ansible.builtin.password', '/tmp/final-project/mysql_root_password', chars=['ascii_letters', 'digits', 'punctuation'], length=20) }}"
    db_user_pass: "{{ lookup('ansible.builtin.password', '/tmp/final-project/db_user_pass', chars=['ascii_letters', 'digits', 'punctuation'], length=20) }}"
    borg_passwd: "{{ lookup('ansible.builtin.password', '/tmp/final-project/borg_passwd', chars=['ascii_letters', 'digits'], length=20) }}"
    syslog_password: "{{ lookup('ansible.builtin.password', '/tmp/final-project/syslog_password', chars=['ascii_letters', 'digits', 'punctuation'], length=20) }}"
    auth_key: "{{ lookup('ansible.builtin.password', '/tmp/final-project/auth_key', chars=['ascii_letters', 'digits', 'punctuation'], length=64) }}"
    secure_auth_key: "{{ lookup('ansible.builtin.password', '/tmp/final-project/secure_auth_key', chars=['ascii_letters', 'digits', 'punctuation'], length=64) }}"
    logged_in_key: "{{ lookup('ansible.builtin.password', '/tmp/final-project/logged_in_key', chars=['ascii_letters', 'digits', 'punctuation'], length=64) }}"
    nonce_key: "{{ lookup('ansible.builtin.password', '/tmp/final-project/nonce_key', chars=['ascii_letters', 'digits', 'punctuation'], length=64) }}"
    auth_salt: "{{ lookup('ansible.builtin.password', '/tmp/final-project/secure_auth_salt', chars=['ascii_letters', 'digits', 'punctuation'], length=64) }}"
    secure_auth_salt: "{{ lookup('ansible.builtin.password', '/tmp/final-project/secure_auth_salt', chars=['ascii_letters', 'digits', 'punctuation'], length=64) }}"
    logged_in_salt: "{{ lookup('ansible.builtin.password', '/tmp/final-project/logged_in_salt', chars=['ascii_letters', 'digits', 'punctuation'], length=64) }}"
    nonce_salt: "{{ lookup('ansible.builtin.password', '/tmp/final-project/nonce_salt', chars=['ascii_letters', 'digits', 'punctuation'], length=64) }}"
    delegate_to: "{{ ansible_play_hosts }}"
    run_once: yes

...