---
- name: "Install epel-release"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - epel-release
    - audispd-plugins

- name: "Set timezone"
  timezone:
    name: "{{ ntp_timezone }}"

- name: "Force timesync with chrony"
  shell: "chronyc -a makestep"

- name: "Enable and start firewalld"
  systemd:
    name: firewalld
    state: started
    enabled: true

- name: "Configuring firewall services"
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: disabled
    immediate: yes
  with_items:
    - "cockpit"
    - "dhcpv6-client"

- name: "Configure hosts file"
  template:
    dest: /etc/hosts
    src: hosts.j2
    owner: root
    group: root
    mode: 0644

- name: Append json-template to rsyslog
  copy:
    dest: /etc/rsyslog.d/json-template.conf
    src: json-template.conf
    owner: root
    group: root
    mode: 0644

- name: Configure to send logs
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify:
    - restart rsyslog

- name: Configure AUDITD rules
  copy:
    dest: /etc/audit/audit.rules
    src: audit.rules
    owner: root
    group: root
    mode: 0640

- name: Configure AUDITD
  copy:
    dest: /etc/audit/auditd.conf
    src: auditd.conf
    owner: root
    group: root
    mode: 0640

- name: Configure AUDITD plugin to send auditd logs
  copy:
    dest: /etc/audit/plugins.d/au-remote.conf
    src: au-remote.conf
    owner: root
    group: root
    mode: 0640

- name: Configure to send audit logs
  template:
    src: audisp-remote.conf.j2
    dest: /etc/audit/audisp-remote.conf
  notify:
    - restart auditd

- name: "Enable interconnect ports for Prometheus server"
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ frontend_loc_ip }}" port port="9100" protocol="tcp" accept'
    zone: public
    permanent: true
    immediate: true
    state: enabled
  when:
    - "ansible_hostname != frontend"
...