ntp_timezone: "Asia/Bishkek"

cluster_name: "myhacluster"
localnet: "10.10.0.0/24"
node1: "pcmk1"
node1_ip: "10.10.0.101"
node2: "pcmk2"
node2_ip: "10.10.0.102"
nodes_net: "10.10.0.100/255.255.255.252"
clusterip: "10.10.0.120"
hosted_machine: "192.168.50.1"
db_server: "mysql"
mysql_ip: "10.10.0.110"

syslog_server: "syslog"
syslog_ip: "10.10.0.200"

db_name: "wordpress_db"
db_user: "wordpress_user"

drbd_vg: "drbd-vg01"
drbd_lv: "drbd1"

frontend_loc_ip: "10.10.0.10"
frontend_dmz_ip: "192.168.50.100"
frontend: "nginx"
backend_port: "9000"
backup_server_ip: "10.10.0.110"

borg_vg: "borg_vg01"
borg_lv: "borg_lv01"
prometheus_targets:
  node:
  - targets:
    - "{{ frontend }}:9100"
    - "{{ db_server }}:9100"
    - "{{ node1 }}:9100"
    - "{{ node2 }}:9100"
    - "{{ syslog_server }}:9100"
    labels:
      env: final-project
alertmanager_route:
  receiver: stardata-telegram
  routes:
    - receiver: stardata-telegram
      match:
        severity: test-telegram
alertmanager_receivers:
  - name: 'stardata-telegram'
    telegram_configs:
      - bot_token: 6115317598:AAGM-STQCCGg8mnYh8p0P78U0EIOVuYDKxQ
        api_url: https://api.telegram.org
        chat_id: 5157512311
        parse_mode: ''