- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: restart auditd
  command: /usr/sbin/service auditd restart

- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted

- name: restart logstash
  systemd:
    name: logstash
    state: restarted

- name: restart kibana
  systemd:
    name: kibana
    state: restarted