---
- name: "Generating vars and passwords for final-project"
  hosts: all
  become: true
  roles:
    - gen-vars
  tags: gen-vars

- name: "Install and configure hosts"
  hosts: final_project_hosts
  become: true
  roles:
    - host-preparation
  tags: host-preparation

- name: "Install and configure Mariadb Server"
  hosts: db
  become: true
  roles:
    - mysql-config
    - backup-setup
  tags: mysql-config

- name: Install Prometheus monitoring and alerting server
  hosts: frontend
  become: true
  roles:
    - nginx-setup
    - prometheus.prometheus.prometheus
    - prometheus.prometheus.alertmanager
    - grafana-setup
  tags: frontend_servers

- name: "Install and configure Cluster software, Active/Active Storage, Backend for Wordpress"
  hosts: backend
  become: true
  roles:
    - cluster-setup
    - storage-config
    - webserver-config
  tags: beckend-setup

- name: "Install and configure Syslog server"
  hosts: syslog_servers
  become: true
  roles:
    - syslog-setup
  tags: syslog-setup

- name: "Install and configure servers for BackupClient"
  hosts: final_project_hosts
  become: true
  roles:
    - syslog-client
    - backup-client
    - prometheus.prometheus.node_exporter
  tags: client_servers

# - name: "Cleaning up hosted_machine"
#   hosts: hosted_machine
#   become: true
#   tasks:
#     - name: Delete tmp dir
#       ansible.builtin.file:
#         path: /tmp/final-project/
#         state: absent
#   tags: clean-tmp
...
